
export const CREATE_EVENT = (lang) => lang === 'heb' ? 'יצירת אירוע' : 'Create event'
export const TOOLBAR_LOGIN = (lang) => lang === 'heb' ? 'התחברות ' : 'Sign in'
export const TOOLBAR_LANGUAGE = (lang) => lang === 'heb' ? 'שפה ' : 'Language'
export const TOOLBAR_MENU = (lang) => lang === 'heb' ? 'תפריט' : 'Menu'
export const CREATE_RIDE = (lang) => lang === 'heb' ? 'צור הסעה' : 'Create a ride'
export const NO_RIDES = (lang) => lang === 'heb' ? 'לאירוע זה תרם קיימות הסעות, לחץ כאן על מנת ליצור ביקוש להסעה' : 'This event currently has no rides, make a request to create a ride'
export const CANT_SEE_YOUR_CITY = (lang) => lang === 'heb' ? 'לא רואה את העיר שלך ברשימה? לחץ על הכפתור ופתח ביקוש' : 'Your city is missing? lets open a request for a ride'
export const RIDE_DATE = (lang) => lang === 'heb' ? 'תאריך הסעה' : 'Ride Date'
export const STARTING_POINT = (lang) => lang === 'heb' ? 'כל נקודות היציאה' : 'All starting points'
export const STARTING_POINT_SINGLE = (lang) => lang === 'heb' ? 'נקודת היציאה' : 'Starting point'

export const CONTINUE_TO_SECURE_PAYMENT = (lang) => lang === 'heb' ? 'עבור למסך תשלום מאובטח' : 'Continue to secure payment'
export const PICK_START_POINT_REQUEST = (lang) => lang === 'heb' ? 'אנא בחר נקודת יציאה' : 'Please select starting point'

export const FILL_ALL_FIELDS = (lang) => lang === 'heb' ? 'אנא מלא את כל השדות הדרושים' : 'Please fill all required fields'
export const CONTINUE_TO_CREATE = (lang) => lang === 'heb' ? 'בצע יצירת אירוע !' : 'Complete event creation'
export const ATTENTION = (lang) => lang === 'heb' ? 'שימו לב !' : 'Attention !'
export const NO_DELAYS = (lang) => lang === 'heb' ? 'ההסעות יוצאות בדיוק בשעה שנקבעה, לכן אין איחורים' : 'The rides leave exactly at the scheduled moment'
export const DESTINATION_POINT = (lang) => lang === 'heb' ? 'בחר יעד ' : 'Choose Destination'
export const EXTRA_STOP_POINTS = (lang) => lang === 'heb' ? 'נקודות אסיפה נוספות' : 'Extra stop points'
export const PASSENGERS = (lang) => lang === 'heb' ? 'מספר נוסעים' : 'Number of passengers'
export const NAME_OF_RIDE = (lang) => lang === 'heb' ? 'שם ההסעה' : 'Name of ride'
export const SHARE_PAYMENT = (lang) => lang === 'heb' ? 'אני רוצה לחלק את התשלום בין הנוסעים' : 'Shared payment'
export const I_PAY = (lang) => lang === 'heb' ? 'הכל עלי !' : 'I Pay it all !'


export const PICK_IMAGE = (lang, create) => lang === 'heb' ? (create ? 'שנה גרפיקה' : 'בחר תמונה') : 'Select image'
export const CONTINUE = (lang) => lang === 'heb' ? 'המשך' : 'Continue'
export const CULTURE = (lang) => lang === 'heb' ? 'תרבות ופנאי' : 'Culture & Leisure'
export const CLUBS = (lang) => lang === 'heb' ? 'מועדונים' : 'Clubs'
export const SCHEDULED_EVENTS = (lang) => lang === 'heb' ? 'אירועים קרובים' : 'Upcomming Events'

export const MY_ACCOUNT = (lang) => lang === 'heb' ? 'האזור שלי' : 'My Account'
export const REGISTER_TITLE = (lang) => lang === 'heb' ? 'הרשמה' : 'Register'
export const REGISTER_OK = (lang) => lang === 'heb' ? 'הירשם/י' : 'Register'
export const LOGIN_OK = lang => lang === 'heb' ? 'התחבר/י' : 'Sign in'
export const LOGOUT = (lang) => lang === 'heb' ? 'התנתק' : 'Sign out'
export const MENU_ITEM_1 = (lang) => lang === 'heb' ? "אודות" : "About us"
export const MENU_ITEM_2 = (lang) => MY_ACCOUNT(lang)
export const MENU_ITEM_3 = (lang) => lang === 'heb' ? "היסטוריית הסעות" : 'Ride history'
export const MENU_ITEM_4 = (lang) => lang === 'heb' ? "חדש ב Pick n Pull" : 'New at Pick n Pull'
export const MENU_ITEM_5 = (lang) => lang === 'heb' ? "סגור" : 'Close'

export const MY_ACCOUNT_ITEM_1 = (lang) => lang === 'heb' ? 'מטבעות שצברתי' : 'Coins ive earned'
export const MY_ACCOUNT_ITEM_2 = (lang) => lang === 'heb' ? 'קופונים והטבות' : 'Coupons and discounts'
export const MY_ACCOUNT_ITEM_3 = (lang) => lang === 'heb' ? 'היסטוריית נסיעות' : 'Rides history'
export const MY_ACCOUNT_ITEM_4 = (lang) => lang === 'heb' ? 'הגדרות' : 'Settings'
export const EMAIL = (lang) => lang === 'heb' ? 'כתובת אימייל' : 'Email address'
export const PASSWORD = (lang) => lang === 'heb' ? 'סיסמא' : 'Password'
export const OR = (lang) => lang === 'heb' ? 'או' : 'or'

export const NO_ACCOUNT = (lang) => lang === 'heb' ? 'משתמש חדש? הרשם כאן' : 'New user? Register here'
export const ALREADY_REGISTERED = (lang) => lang === 'heb' ? 'משתמש ותיק? התחבר כאן' : 'Already have an account? Login'
export const FORGOT_PASSWORD = (lang) => lang === 'heb' ? 'שכחתי סיסמא' : 'Forgot Password'

export const LOADING = (lang) => lang === 'heb' ? 'טוען..' : 'Loading..'
export const FULL_NAME = (lang) => lang === 'heb' ? 'שם מלא' : 'Full name'
export const FIRST_NAME = (lang) => lang === 'heb' ? 'שם פרטי' : 'First name'
export const LAST_NAME = (lang) => lang === 'heb' ? 'שם משפחה' : 'Last name'
export const BIRTH_DATE = (lang) => lang === 'heb' ? 'תאריך לידה' : 'Birth date'
export const PHONE_NUMBER = (lang) => lang === 'heb' ? 'מספר טלפון' : 'Phone number'

export const PICK = (lang) => lang === 'heb' ? 'בחר' : 'Confirm'
export const PICKED = (lang) => lang === 'heb' ? 'בחירה: ' : 'Selected: '
export const PICK_FAVORITE_EVENTS = (lang) => lang === 'heb' ? 'מהם סוגי האירועים האהובים עלייך ?' : 'What are your favorite type of events ? '
export const OPEN_FAVORITE_EVENTS_DIALOG = (lang) => lang === 'heb' ? 'בחר/י את סוגי אירועים עלייך' : 'Pick your favorite type of events'
export const PICK_FAVORITE_1 = (lang) => lang === 'heb' ? 'מסיבות ומועדונים' : 'Clubs and parties'
export const PICK_FAVORITE_2 = (lang) => lang === 'heb' ? 'משחקי כדורגל' : 'Football games'
export const PICK_FAVORITE_3 = (lang) => lang === 'heb' ? 'הופעות' : 'Shows and Conserts'
export const PICK_FAVORITE_4 = (lang) => lang === 'heb' ? 'פסטיבלים' : 'Fetivals'
export const PICK_FAVORITE_5 = (lang) => lang === 'heb' ? 'ברים' : 'Bars'
export const PICK_FAVORITE_6 = (lang) => lang === 'heb' ? 'ספורט כללי' : 'Sports'
export const PICK_FAVORITE_7 = (lang) => lang === 'heb' ? 'אירועי ילדים' : 'Children Events'
export const SHOW_RIDE_SELECT = (lang) => lang === 'heb' ? 'בחר נקודת יציאה' : 'Select a starting point'
export const SHOW_EXTRA_DETAILS = (lang) => lang === 'heb' ? 'הצג פרטים נוספים' : 'Show details'
export const HIDE_EXTRA_DETAILS = (lang) => lang === 'heb' ? 'הסתר פרטים נוספים' : 'Hide details'
export const START_DATE = (lang) => lang === 'heb' ? 'מועד התחלה: ' : 'Event start date time: '
export const ADDRESS = (lang) => lang === 'heb' ? 'כתובת: ' : 'Address: '
export const TICKET_PRICE = (lang) => lang === 'heb' ? 'מחיר כרטיס' : 'Ticket Price'
export const EVENT_DETAILS = (lang) => lang === 'heb' ? 'פרטי אירוע: ' : 'Event Details: '
export const ORDER = (lang) => lang === 'heb' ? 'הזמן כרטיסים' : 'Order tickets'
export const CURRENCY = (lang) => lang === 'heb' ? `ש"ח` : 'NIS'
export const AGES = (lang) => lang === 'heb' ? 'גילאים' : 'Ages'
export const CLOSE = (lang) => lang === 'heb' ? 'סגור' : 'Close'
export const BOTH_DIRECTIONS = (lang) => lang === 'heb' ? 'סוג הסעה זו הינה דו כיוונית הלוך וחזור' : 'The ticket is a two way ticket'
export const TOTAL_COST = (lang) => lang === 'heb' ? 'סה"כ לתשלום' : 'Total'
export const SIDE = (lang) => lang === 'heb' ? 'rtl' : 'ltr'

export const WHY_US_TITLE = (lang) => lang === 'heb' ? '? למה לבחור בנו' : 'Why choose us ?'
export const WHY_US_ITEM_1_TITLE = (lang) => lang === 'heb' ? 'חוסכים לך כסף' : 'Saving you money'
export const WHY_US_ITEM_1_CONTENT = (lang) => lang === 'heb' ? 'השירות שאנו מספקים הוא זול ומתאים לכל כיס.' : 'Our service is crafted to be affordable for any one'

export const WHY_US_ITEM_2_TITLE = (lang) => lang === 'heb' ? 'חוסכים לך כאב ראש' : 'Sparing you the headache'
export const WHY_US_ITEM_2_CONTENT = (lang) => lang === 'heb' ? 'לא עוד חיפוש חנייה, לא דוחות ולא נהג תורן.' : 'No more looking for parking spot, no tickets and no duty driver'

export const WHY_US_ITEM_3_TITLE = (lang) => lang === 'heb' ? 'חוסכים לך זמן' : 'Saving you time'
export const WHY_US_ITEM_3_CONTENT = (lang) => lang === 'heb' ? 'לא תצטרכו להמתין בעשרות נקודות עצירה.' : 'You wont have to go through to many stop points'

export const WHY_US_ITEM_4_TITLE = (lang) => lang === 'heb' ? 'מפנקים אותך' : 'Spoiling you'
export const WHY_US_ITEM_4_CONTENT = (lang) => lang === 'heb' ? 'Pick N Pull מעניקה לך שלל הטבות, מבצעים וקופונים.' : 'Pick N Pull offers you a wide range of discounts and special offers'

export const WHY_US_ITEM_5_TITLE = (lang) => lang === 'heb' ? '!don’t drink and drive' : '!don’t drink and drive'
export const WHY_US_ITEM_5_CONTENT = (lang) => lang === 'heb' ? 'אנחנו מאמינים שצריך להנות מבלי לקחת סיכונים מיותרים, החיים יקרים!' : 'We believe in having fun without taking stupid risks, life is too precious!'

export const WHY_US_ITEM_6_TITLE = (lang) => lang === 'heb' ? 'מערכת יחסים ארוכה' : 'Long term relationshop'
export const WHY_US_ITEM_6_CONTENT = (lang) => lang === 'heb' ? 'בכל נסיעה תצברו נקודה, ולאחר 5 נקודות תוכלו לממש אותן ולקבל נסיעה חינם!' : 'Each ride you take, you gain points too use in your next rides!'


export const NO_MORE_ITEM_1 = (lang) => lang === 'heb' ? 'נהג תורן' : 'Duty Driver'
export const NO_MORE_ITEM_2 = (lang) => lang === 'heb' ? 'חניונים במחירים מטורפים' : 'Expensive parking lots'
export const NO_MORE_ITEM_3 = (lang) => lang === 'heb' ? 'drink & drive' : 'drink & drive'
export const NO_MORE_ITEM_4 = (lang) => lang === 'heb' ? 'מוניות יקרות' : 'Expensive cabs'
export const NO_MORE_ITEM_5 = (lang) => lang === 'heb' ? 'מחסור בדרכי הגעה בלילות וסופי שבוע' : 'Lack of arriving ways on weekends'

export const CREATE_EVENT_TITLE = (lang) => lang === 'heb' ? 'יצירת אירוע' : 'Create event'
export const EVENT_TITLE = (lang) => lang === 'heb' ? 'כותרת האירוע' : 'Event title'
export const EVENT_ADDRESS = (lang) => lang === 'heb' ? 'כתובת האירוע' : 'Event address'
export const EVENT_START = (lang) => lang === 'heb' ? 'תחילת האירוע' : 'Event start date'
export const EVENT_END = (lang) => lang === 'heb' ? 'סיום האירוע' : 'Event end date'
export const EVENT_TYPE = (lang) => lang === 'heb' ? 'סוג האירוע' : 'Event type'
export const EVENT_DESC = (lang) => lang === 'heb' ? 'תיאור האירוע' : 'Event description'


export const MY_NAME = (lang) => lang === 'heb' ? 'שם' : 'Name'
export const MY_COINS = (lang) => lang === 'heb' ? 'מטבעות PNP' : 'Coins'